const realSciences = [
   // 'Dasturlash',
   // 'Geometriya',
   // 'Tarix',
   'English',
]

const ALL_QUESTIONS = {
   English: {
      questions: [
         "Fill in the gaps using the relative pronouns: I was invited by the professor________ I met at the conference.",
         "Fill in the gaps using the relative pronouns: I don’t like the table ________ stends in the kitchen.",
         "Fill in the gaps using the relative pronouns: Service management is a system ________ connects actual company sales and the customer",
         "Fill in the gaps using the relative pronouns: A waiter ________ served you was very polite.",
         "Fill in the gaps using the relative pronouns: I shell never forget that day________ our company won a tender.",
         "Fill in the gaps using the relative pronouns: Car wash is a service ________ provides sanitary service.",
         "Fill in the gaps using the relative pronouns: Generally, service management comprises six different capabilities ________ companies should consider for optimization.",
         "Fill in the gaps using the relative pronouns: Among all I have found the itinerary ________has been offered by the Uzbek Tourism Company the most preferable.",
         "Fill in the gaps using the relative pronouns: Wedding service is a service ________ offers decorations of wedding restaurants, taking videos and photos and karnay – sunray musical instruments.",
         "Fill in the gaps using the relative pronouns: You can fiend the client at the cash desk ________ he is waiting for his turn ",
         "Match the words with their definition. “help or support”",
         "Match the words with their definition. “ an opinion which someone offers you”",
         "Match the words with their definition. “ the feeling of being certain that something exists or is true”",
         "Match the words with their definition. “ money which is owed to someone else”",
         "Match the words with their definition. “ unequal”",
         "Match the words with their definition. “ clearly shown”",
         "Match the words with their definition. “ rationally”",
         "Match the words with their definition. “ influence”",
         "Match the words with their definition. “ to get back something lost”",
         "Match the words with their definition. “ to harm or spoil something”",
         "Fill in the gaps with words. It is important to research various sources of information to ________________ with your goals in personal development.",
         "Fill in the gaps with words. Taking more breaks actually gives your mind a chance to ____________, allowing you to return and work more____________________.",
         "Fill in the gaps with words. You must know your _______________ are in order to make a self improvement plan. It wouldn’t make sense to work on areas of your life.",
         "Fill in the gaps with words. Stress can_______________________ your body, so take it all in single step.",
         "Fill in the gaps with words. Make a target goal for yourself. Goals that are specifcally________________ will have specifc results",
         "Fill in the gaps with words. Make a target goal for yourself. Goals that are specifcally________________ will have specifc results",
      ],
      answers: [
         ['where', 'who', 'whom', 'that'],
         ['whom', 'that', 'who', 'where'],
         ['whom', 'where', 'who', 'that'],
         ['who', 'whom', 'where', 'that'],
         ['whom', 'which', 'who', 'where'],
         ['whom', 'who', 'which', 'where'],
         ['whom', 'who', 'where', 'which'],
         ['whom', 'which', 'where', 'who'],
         ['which', 'whom', 'where', 'who'],
         ['that', 'whom', 'where', 'who'],
         ['advice', 'aid', 'debt', 'unique'],
         ['aid', 'unique', 'affect', 'advice'],
         ['affect', 'belief', 'unique', 'aid'],
         ['affect', 'debt', 'unique', 'aid'],
         ["aid", "affect", "unique", "debt"],
         // !!!!!!!!
         ["define", "affect", "debt", "aid"],
         ["affect", "effciently", "debt", "aid"],
         ["affect", "aid", "effect", "debt"],
         ["recover", "aid", "affect", "debt"],
         ["debt", "aid", "affect", "damage"],
         ["debt", "aid", "define", "affect"],
         ["debt", "recover, effciently", "Aid,damage", "affect"],
         ["damage", "affect", "aid", "debt"],
         ["debt", "damage", "aid", "affect"],
         ["beliefs", "debt", "affect", "aid"],
         ["aid", "debt", "beliefs", "affect"],
      ],
      correctAnswers: [3, 2, 4, 1, 2, 3, 4, 2, 1, 3, 2, 4, 2, 2, 3, 1, 2, 3, 1, 4, 3, 2, 4, 2, 1, 3]
   },
}
// test english - 26